// Static text/labels and templates for plea, primary FS, final FS in EN/GU
export const T = {
  en: {
    appTitle: "ACJM Court Solution",
    selectLanguage: "Select the Language of Plea",
    enterAccused: "Enter Accused Details",
    fields: {
      case_no: "Criminal Case No.",
      name: "Full Name of the Accused",
      father_husband: "Full Name of Father / Husband",
      religion: "Religion",
      age: "Age",
      occupation: "Occupation",
      address: "Address",
      contact: "Contact No.",
    },
    addressHint: "H. No. -, Society / Vas / Faliya, Landmark, Area / Locality / Village, Tehsil / Taluka, District, State, Pin",
    selectCharge: "Select the Charge",
    chargeOptions: {
      "138": "Sec. 138 of The Negotiable Instruments Act, 1881",
      "25": "Sec. 25 of The Payment & Settlement Systems Act, 2007",
    },
    q1: "Question No. 1 - Have you received the copy of complaint and other case papers?",
    q2_138: "The allegations of the complainant of the matter against you are such that, you the accused of the matter have issued the disputed cheque/s (as mentioned within the complaint) in favour of the complainant in discharge of legal debt or liability. However, when the complainant of the matter has deposited the cheque/s with his bank, the disputed cheque/s was / were returned dishonoured by your banker assigning the reason/s mentioned within the cheque return memo and complaint. Though the complainant of the matter has duly served statutory demand notice upon you, demanding the cheque/s amount, you have neglected to make the payment of the amount mentioned within the cheques/s within such period prescribed by law. Hence, you have committed the offence U/Sec. 138, of The Negotiable Instruments Act, 1881. Do you plead Guilty?",
    q2_25: "The allegations of the complainant of the matter against you are such that, you the accused of the matter have issued the instruction of EFT (Electronic Fund Transfer) / ECS (as mentioned within the complaint) in favour of the complainant in discharge of legal debt or liability. However, when the complainant of the matter has initiated such EFT / ECS through his bank, the disputed EFT / ECS was returned dishonoured by your banker assigning the reason/s mentioned within the return memo and complaint. Though the complainant of the matter has duly served statutory demand notice upon you, demanding the EFT / ECS amount, you have neglected to make the payment of the amount mentioned within such instructions within such period prescribed by law. Hence, you have committed the offence U/Sec. 25, of The Payment & Settlement Systems Act, 2007. Do you plead Guilty?",
    q2Options: ["Yes I Plead Guilty for the Offence", "No, I Don't plead guilty and I wish to get tried for the offence"],
    yesNo: ["Yes", "No"],
    sanjabi: {
      q3: "Question 3 - Do you admit that the cheque belongs to your account?",
      q4: "Question 4 - Do you admit that the signature on the cheque is yours?",
      q5: "Question 5 - Did you issue/deliver this cheque to the complainant?",
      q6: "Question 6 - Do you admit that you owed liability to the complainant at the time of issuance?",
      q7: "Question 7 - If you deny liability, state clearly the defence?",
      q7opts: ["Security cheque only.", "Loan repaid already", "Cheque altered/misused", "Other (specify)"],
      q8: "Question 8 - Do you wish to compound the case at this stage?",
    },
    btnPleaSanjabi: "Plea as per Sanjabi Tari Judgment",
    btnPleaNormal: "Normal Plea",
    edit: "Edit", proceed: "Proceed", submit: "Submit", print: "Print",
    pleaTitle: "Plea of the Accused.",
    fsTitle: "Further Statement of the above-named accused under Section 313 of the Code of Criminal Procedure, 1973 / Section 351 of the BNSS, 2023 (in Question-Answer form).",
    primaryQ1: "Have you received all the case papers?",
    primaryQ2_138: "As per the deposition on oath given by the complainant witness in the present case, due to existence of narrated transaction within the oath of the complainant witness, the complainant had legally enforceable debt / liability against you. In discharge of such debt / liability, you issued a cheque/s described within the oath, upon presentation of such instrument with your banker, within it validity, the instrument was return unpaid by your banker for the reasons enumerated within return memo. Thereafter despite of due service of statutorily valid demand notice, you have neglected to make pay the amount mentioned within the cheque within such prescribed period by law and therefore the present complaint has been filed before this Court. In this respect, what do you want to state by way of explanation or defence?",
    primaryQ2_25: "As per the deposition on oath given by the complainant witness in the present case, due to existence of narrated transaction within the oath of the complainant witness, the complainant had legally enforceable debt / liability against you. In discharge of such debt/ liability, you issued a EFT / ECS mandate (instruction) as described within the oath, upon presentation of such EFT / ECS with your banker, within it validity, of such EFT / ECS was return unpaid by your banker for the reasons enumerated within return memo. Thereafter despite of due service of statutorily valid demand notice, you have neglected to make pay the amount mentioned within the EFT / ECS within such prescribed period by law and therefore the present complaint has been filed before this Court. In this respect, what do you want to state by way of explanation or defence?",
    primaryQ3: "In view of the judgment of the Hon'ble Supreme Court in *Meters and Instruments Private Limited versus Kanchan Mehta*, 2017 (0) AIJEL-SC 60915, you are required to disclose your specific defence in the present case. What is your specific defence?",
    primaryQ4: "Do you wish to state anything further in your defence?",
    beforeMe: "Before Me",
    readOver: "The above statement is read over and explained to the accused, who admits that it is true and correct.",
  },
  gu: {
    appTitle: "મહે. ACJM ન્યાયાલય સોલ્યુશન",
    selectLanguage: "પ્લી ની ભાષા પસંદ કરો",
    enterAccused: "::આરોપી લગત વિગતો::",
    fields: {
      case_no: "ફોજ. કેસ. ન.",
      name: "આરોપી નું પુરૂ નામ",
      father_husband: "આરોપી ના પિતા / પતિ નું પુરૂ નામ",
      religion: "જાતિ",
      age: "ઉમર",
      occupation: "વ્યવસાય",
      address: "સરનામું",
      contact: "સંપર્ક સંખ્યા",
    },
    addressHint: "મ. ન.–, સોસાયટી / વાસ / ફળિયું, નજીક માં આવેલ પ્રખ્યાત જગ્યા, વિસ્તાર / ગામ, તાલુકો, જિલ્લો, રાજ્ય, પીન કોડ",
    selectCharge: "તહોમત નામું પસંદ કરો",
    chargeOptions: {
      "138": "કલમ. ૧૩૮ ધી. નેગો ઇન્સ્ટ્રુમેન્ટ એક્ટ, ૧૮૮૧",
      "25": "કલમ ૨૫ ધી. પેમેન્ટ અને સેટલમેન્ટ સીસ્ટમ એક્ટ, ૨૦૦૭",
    },
    q1: "પ્રશ્ન ૧ - શું તમો ને ફરિયાદ અને બચાવ માટે જરૂરી દસ્તાવેજી નકલો મળી ગયેલ છે?",
    q2_138: "ફરિયાદ પક્ષ તરફે તમારા ઉપર આવો આરોપ છે કે, તમો આરોપીએ હાલના કામના ફરિયાદી ને તેઓના કાયદેસર ના લેણાં / દેવા ની ચુકવણી પેટે હાલના કામે ફરિયાદ માં રહેલ વર્ણન મુજબ નો તમારા બેન્ક ખાતા નો તકરારી ચેક/ઑ, તેમાં રહેલ રકમ ની વસૂલાત માટે ફરિયાદી ને સોંપી આપેલ હતો. આ ચેક /ઑ ફરિયાદી દ્વારા લેણી રકમ વસૂલ લેવા માટે જમા કરવામાં આવતા, તમારા બેંક દ્વારા ફરિયાદ અને ચેક રીટર્ન મેમો માં રહેલ શેરા સાથે ફરિયાદ માં જણાવેલ તારીખ ના રોજ ના ચેક રિટર્ન મેમો સાથે પરત કરેલ છે, અને તે ચેક ની રકમ ની માંગણી ફરિયાદી દ્વારા તમારી સામે કાયદેસર ની નોટીસ મોકલી કરવામાં આવેલ હોવા છતા, તમો નિયત સમય મર્યાદામાં ઉપરોક્ત જણાવેલ રકમ ચુકવવામાં કસૂર કરેલ હોઇ, તમોએ ધી નેગોશીયેબ્લ ઇન્સ્ટ્રુમેન્ટ એકટ, ૧૮૮૧ ની કલમ, ૧૩૮ મુજબ નો ગુનો કરેલ છે, શું તમો ને તે મુજબ નો ગુનો કબૂલ છે?",
    q2_25: "ફરિયાદ પક્ષ તરફે તમારા ઉપર આવો આરોપ છે કે, તમો આરોપીએ હાલના કામના ફરિયાદી ને તેઓના કાયદેસર ના લેણાં / દેવા ની ચુકવણી પેટે હાલના કામે ફરિયાદ માં રહેલ વર્ણન મુજબ નો તમારા બેન્ક ખાતા નો તકરારી EFT / ECS, તેમાં રહેલ રકમ ની વસૂલાત માટે ફરિયાદી ને સોંપી આપેલ હતો. આ EFT / ECS ફરિયાદી દ્વારા લેણી રકમ વસૂલ લેવા માટે જમા કરવામાં આવતા, તમારા બેંક દ્વારા ફરિયાદ અને રીટર્ન મેમો માં રહેલ શેરા સાથે ફરિયાદ માં જણાવેલ તારીખ ના રોજ ના રિટર્ન મેમો સાથે પરત કરેલ છે, અને તે EFT / ECS ની રકમ ની માંગણી ફરિયાદી દ્વારા તમારી સામે કાયદેસર ની નોટીસ મોકલી કરવામાં આવેલ હોવા છતા, તમો નિયત સમય મર્યાદામાં ઉપરોક્ત જણાવેલ રકમ ચુકવવામાં કસૂર કરેલ હોઇ, તમોએ પેમેન્ટ અને સેટલમેન્ટ સીસ્ટમસ અધિનિયમ, ૨૦૦૭ ની કલમ, ૨૫ મુજબ નો ગુનો કરેલ છે, શું તમો ને તે મુજબ નો ગુનો કબૂલ છે?",
    q2Options: ["હાજી હું ગુનો કબૂલ કરૂ છું", "નાજી સાહેબ, મને ગુનો કબૂલ નથી, મને કેસ આગળ ચલાવવી છે."],
    yesNo: ["હા", "ના"],
    sanjabi: {
      q3: "પ્રશ્ન ૩ - શું તમે કબૂલ કરો છો કે, તકરારી ચેક/ચેકો તમારા બેન્ક ખાતા ના આવેલા છે?",
      q4: "પ્રશ્ન ૪ - શું તમે કબૂલ કરો છો કે, તકરારી ચેક/ચેકો માં આવેલ સહી તમારી છે?",
      q5: "પ્રશ્ન ૫ - શું તમે તકરારી ચેક / ચેકો આ કામના ફરિયાદી ને સુપરત કરેલ છે?",
      q6: "પ્રશ્ન ૬ - શું તમે કબૂલ કરો છો કે, ચેક સુપરત કરતી વખતે ફરિયાદી નું તમારી સામે કાયદેસર નું લેણું આવેલ હતું?",
      q7: "પ્રશ્ન ૭ - જો તમો ફરિયાદી નું તમારી સામે કાયદેસર નું લેણું આવેલ હોવાનું ઇનકાર કરતાં હોય તો, તમારો વિશિષ્ટ પ્રકાર નું બચાવ રજૂ કરશો?",
      q7opts: ["જામીની / સિક્યુરીટી પેટે આપેલ ચેક / ચેકો છે", "લોન ની સમગ્ર ભરપાઈ અગાઉ થી થઈ ગયેલ છે", "ચેક / ચેકો માં ખોટી રીતે સુધારો / ખોટી રીતે દૂર-ઉપયોગ કરવા માં આવેલ છે", "અન્ય (વિગતો જણાવો)"],
      q8: "પ્રશ્ન ૮ - શું હાલના તબક્કે કેસ માંડવાળ થી પૂર્ણ કરવા માંગો છો?",
    },
    btnPleaSanjabi: "Plea as per Sanjabi Tari Judgment",
    btnPleaNormal: "Normal Plea",
    edit: "સુધારો", proceed: "સાથે આગળ વધવું છે", submit: "મોકલો", print: "પ્રિન્ટ",
    pleaTitle: "આરોપી નું નિવેદન.",
    fsTitle: "આ જણાવેલ આરોપી નું ફો. કા. સંહિતા, ૧૯૭૩ ની કલમ ૩૧૩ / બી. એન. એસ. એસ. ૨૦૨૩ કલમ ૩૫૧ હેઠળ નું વિશેષ નિવેદન (પ્રશ્ન-ઉત્તર સ્વરૂપ માં).",
    primaryQ1: "શું તમને તમામ કેસ કાગળો પ્રાપ્ત થઈ ગયેલા છે?",
    primaryQ2_138: "હાલના કામના ફરિયાદ પક્ષ ના સાક્ષી એ પોતાની સોગંદ ઉપર ની સર તપાસ માં એમ જણાવેલ છે કે, તમો આરોપી સામે તેમનું કાયદેસર નું લેણું / દેવું આવેલ હોય, તમો આરોપી પક્ષ તરફ થી પ્રાપ્ત થયેલ તકરારી ચેક / ઑ જ્યારે તેમણે રકમ ની વસૂલાત માટે રજૂ કરેલ, ત્યારે આ તકરારી ચેક / ઑ તમારા બેન્ક દ્વારા સોગંદનામાં અને રીટર્ન મેમો માં દર્શાવેલ કારણોસર પરત કરવા માં આવેલ. જેથી આવા ચેક ની રકમ ની માંગણી કરતી કાયદેસર ની નોટીસ ફરિયાદ પક્ષ એ તમો ઉપર નિયત સમય માં મોકલી આપવેલ હોવા છતાં, તમો આરોપી નિયત સમય મર્યાદામાં ચેક માં દર્શાવેલ કૂલ રકમ ની ફરિયાદ પક્ષ ને ચુકવણી કરવા માં કસૂર કરેલ છે. તે બાબતે તમારે શું કહેવું છે?",
    primaryQ2_25: "હાલના કામના ફરિયાદ પક્ષ ના સાક્ષી એ પોતાની સોગંદ ઉપર ની સર તપાસ માં એમ જણાવેલ છે કે, તમો આરોપી સામે તેમનું કાયદેસર નું લેણું / દેવું આવેલ હોય, તમો આરોપી પક્ષ તરફ થી પ્રાપ્ત થયેલ તકરારી ઇ. એફ. ટી / ઇ. સી. એસ. જ્યારે તેમણે રકમ ની વસૂલાત માટે રજૂ કરેલ, ત્યારે આ તકરારી ઇ. એફ. ટી / ઇ. સી. એસ. તમારા બેન્ક દ્વારા સોગંદનામાં અને રીટર્ન મેમો માં દર્શાવેલ કારણોસર પરત કરવા માં આવેલ. જેથી આવા ઇ. એફ. ટી / ઇ. સી. એસ. ની રકમ ની માંગણી કરતી કાયદેસર ની નોટીસ ફરિયાદ પક્ષ એ તમો ઉપર નિયત સમય માં મોકલી આપવેલ હોવા છતાં, તમો આરોપી નિયત સમય મર્યાદામાં ઇ. એફ. ટી / ઇ. સી. એસ. માં દર્શાવેલ કૂલ રકમ ની ફરિયાદ પક્ષ ને ચુકવણી કરવા માં કસૂર કરેલ છે. તે બાબતે તમારે શું કહેવું છે?",
    primaryQ3: "નામ. સર્વોચ્ચ ન્યાયાલય ના Meters And Instruments Private Limited Versus Kanchan Mehta 2017 (0) AIJEL-SC 60915 ચુકાદા મુજબ તમો હાલના કામે તમારૂ વિશિષ્ટ પ્રકાર નું બચાવ રજૂ કરવા બંધાયેલ હોય, તમારૂ હાલના કામે વિશિષ્ટ પ્રકાર નું બચાવ શું રહેલ છે?",
    primaryQ4: "તમો આરોપી ને પોતાના બચાવ માં વિશેષ માં કાંઇ કહેવું છે?",
    beforeMe: "મારી રૂબરૂ",
    readOver: "ઉપરોક્ત નિવેદન આરોપી પક્ષ ને વાંચી સંભળાવતા તે બરાબર અને સાચું તથા ખરૂ હોવાનું કબૂલે છે.",
  },
};
